blueprint:
  name: Motion Time-of-Day Scenes with Override
  description: |
    Schaltet je nach Tageszeit unterschiedliche Szenen per Bewegungsmelder.

    Features:
    - 4 Tageszeit-Szenen (Morgen, Tag, Abend, Nacht) - alle optional
    - Automatischer Szenen-Wechsel bei Tageszeit-Änderung
    - Toggle-Schalter (Wandschalter/Shelly) mit Cooldown
    - Erkennt manuelle Licht-Änderungen (HA-App, andere Apps) → Cooldown
    - Optionale Helligkeitsprüfung (nur bei Dunkelheit aktivieren)
    - Blocker Entity zum Deaktivieren der Automatik
    - Dim-Warnung vor Ausschalten

    WICHTIG: Erstelle einen Timer Helper für den Cooldown!
    (Einstellungen → Helfer → Helfer erstellen → Timer)
  domain: automation
  source_url: https://github.com/hoizi89/ha-blueprints/blob/master/automation/motion_time_of_day_scenes.yaml
  author: hoizi89

  input:
    motion_sensor:
      name: Bewegungsmelder
      description: Binary Sensor für Bewegung
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class:
              - motion
              - occupancy

    target_lights:
      name: Ziel-Lichter
      description: Diese Lichter werden gesteuert.
      selector:
        target:
          entity:
            domain: light

    override_switch:
      name: Wandschalter (Toggle)
      description: Schalter für manuelle Steuerung. Reagiert auf jeden Tastendruck.
      selector:
        entity:
          filter:
            domain:
              - switch
              - input_boolean
              - light
              - binary_sensor

    cooldown_timer:
      name: Cooldown Timer
      description: |
        ERFORDERLICH! Erstelle einen Timer Helper.
        (Einstellungen → Helfer → Helfer erstellen → Timer)
        Dauer egal - wird vom Blueprint gesetzt.
      selector:
        entity:
          filter:
            domain: timer

    override_scene:
      name: Override-Szene
      description: Szene wenn Schalter gedrückt wird und Licht aus ist.
      selector:
        entity:
          filter:
            domain: scene

    morning_scene:
      name: Morgenszene (optional)
      description: Szene für den Morgen. Leer = Licht aus.
      default: []
      selector:
        entity:
          filter:
            domain: scene

    day_scene:
      name: Tagszene (optional)
      description: Szene für den Tag. Leer = Licht aus.
      default: []
      selector:
        entity:
          filter:
            domain: scene

    evening_scene:
      name: Abendszene (optional)
      description: Szene für den Abend. Leer = Licht aus.
      default: []
      selector:
        entity:
          filter:
            domain: scene

    night_scene:
      name: Nachtszene (optional)
      description: Szene für die Nacht. Leer = Licht aus.
      default: []
      selector:
        entity:
          filter:
            domain: scene

    morning_start:
      name: Start Morgen
      default: "06:00:00"
      selector:
        time: {}

    day_start:
      name: Start Tag
      default: "09:00:00"
      selector:
        time: {}

    evening_start:
      name: Start Abend
      default: "18:00:00"
      selector:
        time: {}

    night_start:
      name: Start Nacht
      default: "22:00:00"
      selector:
        time: {}

    off_delay:
      name: Ausschaltverzögerung
      description: Sekunden nach letzter Bewegung bis zum Ausschalten.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          step: 10
          unit_of_measurement: seconds

    cooldown_duration:
      name: Cooldown nach Schalter
      description: Sekunden nach Tastendruck in denen Bewegung ignoriert wird.
      default: 300
      selector:
        number:
          min: 30
          max: 3600
          step: 30
          unit_of_measurement: seconds

    transition_time:
      name: Übergangszeit
      default: 1
      selector:
        number:
          min: 0
          max: 5
          step: 0.5
          unit_of_measurement: seconds

    illuminance_sensor:
      name: Helligkeitssensor (optional)
      description: Nur bei Dunkelheit aktivieren.
      default: []
      selector:
        entity:
          filter:
            domain: sensor
            device_class: illuminance

    illuminance_threshold:
      name: Helligkeitsschwelle
      default: 50
      selector:
        number:
          min: 0
          max: 500
          step: 10
          unit_of_measurement: lx

    blocker_entity:
      name: Blocker (optional)
      description: Wenn ON, ist die komplette Automatik deaktiviert.
      default: []
      selector:
        entity:
          filter:
            domain:
              - input_boolean
              - switch
              - binary_sensor

    dim_before_off:
      name: Dimmen vor Ausschalten
      default: false
      selector:
        boolean: {}

    dim_level:
      name: Dim-Level
      default: 20
      selector:
        number:
          min: 5
          max: 50
          step: 5
          unit_of_measurement: "%"

    dim_duration:
      name: Dim-Dauer
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: seconds

mode: parallel
max: 3
max_exceeded: silent

variables:
  motion_sensor: !input motion_sensor
  cooldown_timer: !input cooldown_timer
  illuminance_sensor: !input illuminance_sensor
  illuminance_threshold: !input illuminance_threshold
  blocker_entity: !input blocker_entity
  morning_scene: !input morning_scene
  day_scene: !input day_scene
  evening_scene: !input evening_scene
  night_scene: !input night_scene
  override_scene: !input override_scene
  transition_time: !input transition_time
  cooldown_duration: !input cooldown_duration
  dim_before_off: !input dim_before_off
  dim_level: !input dim_level
  dim_duration: !input dim_duration
  morning_start: !input morning_start
  day_start: !input day_start
  evening_start: !input evening_start
  night_start: !input night_start

  # Tageszeit-Berechnung
  now_minutes: "{{ now().hour * 60 + now().minute }}"
  morning_minutes: "{{ (morning_start.split(':')[0] | int) * 60 + (morning_start.split(':')[1] | int) }}"
  day_minutes: "{{ (day_start.split(':')[0] | int) * 60 + (day_start.split(':')[1] | int) }}"
  evening_minutes: "{{ (evening_start.split(':')[0] | int) * 60 + (evening_start.split(':')[1] | int) }}"
  night_minutes: "{{ (night_start.split(':')[0] | int) * 60 + (night_start.split(':')[1] | int) }}"

  is_morning: "{{ morning_minutes <= now_minutes < day_minutes }}"
  is_day: "{{ day_minutes <= now_minutes < evening_minutes }}"
  is_evening: "{{ evening_minutes <= now_minutes < night_minutes }}"
  is_night: "{{ now_minutes >= night_minutes or now_minutes < morning_minutes }}"

  # Szenen-Auswahl
  has_morning_scene: "{{ morning_scene | length > 0 }}"
  has_day_scene: "{{ day_scene | length > 0 }}"
  has_evening_scene: "{{ evening_scene | length > 0 }}"
  has_night_scene: "{{ night_scene | length > 0 }}"

  current_scene: >
    {% if is_morning and has_morning_scene %}
      {{ morning_scene }}
    {% elif is_day and has_day_scene %}
      {{ day_scene }}
    {% elif is_evening and has_evening_scene %}
      {{ evening_scene }}
    {% elif is_night and has_night_scene %}
      {{ night_scene }}
    {% else %}
      none
    {% endif %}

  has_current_scene: "{{ current_scene != 'none' }}"

  # Bedingungen
  has_blocker: "{{ blocker_entity | length > 0 }}"
  is_blocked: "{{ has_blocker and states(blocker_entity) == 'on' }}"
  is_cooldown: "{{ states(cooldown_timer) == 'active' }}"
  has_illuminance: "{{ illuminance_sensor | length > 0 }}"
  is_dark: "{{ not has_illuminance or (states(illuminance_sensor) | float(0)) < illuminance_threshold }}"

  can_activate: "{{ not is_blocked and not is_cooldown and is_dark }}"

  # Licht-Status prüfen
  target_lights_input: !input target_lights
  lights_are_on: >
    {% set entities = target_lights_input.entity_id | default([]) %}
    {% set entity_list = [entities] if entities is string else entities %}
    {{ entity_list | select('is_state', 'on') | list | count > 0 }}

triggers:
  - id: motion_on
    trigger: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

  - id: motion_off
    trigger: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"

  - id: switch_toggle
    trigger: state
    entity_id: !input override_switch

  - id: light_changed
    trigger: state
    entity_id: !input target_lights

  - id: time_change
    trigger: time
    at:
      - !input morning_start
      - !input day_start
      - !input evening_start
      - !input night_start

conditions: []

actions:
  - choose:
      # ===== SCHALTER GEDRÜCKT =====
      - conditions:
          - condition: trigger
            id: switch_toggle
        sequence:
          # Cooldown-Timer starten (ersetzt vorherigen Timer automatisch)
          - action: timer.start
            target:
              entity_id: !input cooldown_timer
            data:
              duration: "{{ cooldown_duration }}"

          # Licht togglen
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ lights_are_on }}"
                sequence:
                  - action: light.turn_off
                    target: !input target_lights
                    data:
                      transition: "{{ transition_time }}"
            default:
              - action: scene.turn_on
                target:
                  entity_id: "{{ override_scene }}"
                data:
                  transition: "{{ transition_time }}"

      # ===== LICHT MANUELL GEÄNDERT =====
      - conditions:
          - condition: trigger
            id: light_changed
          - condition: template
            value_template: "{{ not is_cooldown }}"
          - condition: template
            value_template: "{{ trigger.to_state.context.parent_id is none }}"
        sequence:
          # Manuelle Änderung erkannt → Cooldown-Timer starten
          - action: timer.start
            target:
              entity_id: !input cooldown_timer
            data:
              duration: "{{ cooldown_duration }}"

      # ===== BEWEGUNG ERKANNT =====
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: template
            value_template: "{{ can_activate and has_current_scene }}"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: "{{ current_scene }}"
            data:
              transition: "{{ transition_time }}"

      # ===== BEWEGUNG WEG =====
      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - delay:
              seconds: !input off_delay

          # Prüfen ob immer noch keine Bewegung
          - condition: state
            entity_id: !input motion_sensor
            state: "off"

          # Dim-Warnung oder direkt aus
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ dim_before_off }}"
                sequence:
                  - action: light.turn_on
                    target: !input target_lights
                    data:
                      brightness_pct: "{{ dim_level }}"
                      transition: "{{ transition_time }}"

                  - delay:
                      seconds: "{{ dim_duration }}"

                  # Nochmal prüfen - vielleicht wieder Bewegung
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input motion_sensor
                            state: "on"
                          - condition: template
                            value_template: "{{ can_activate and has_current_scene }}"
                        sequence:
                          - action: scene.turn_on
                            target:
                              entity_id: "{{ current_scene }}"
                            data:
                              transition: "{{ transition_time }}"
                    default:
                      - action: light.turn_off
                        target: !input target_lights
                        data:
                          transition: "{{ transition_time }}"
            default:
              - action: light.turn_off
                target: !input target_lights
                data:
                  transition: "{{ transition_time }}"

      # ===== TAGESZEIT WECHSELT =====
      - conditions:
          - condition: trigger
            id: time_change
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
          - condition: template
            value_template: "{{ can_activate }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ has_current_scene }}"
                sequence:
                  - action: scene.turn_on
                    target:
                      entity_id: "{{ current_scene }}"
                    data:
                      transition: "{{ transition_time }}"
            default:
              - action: light.turn_off
                target: !input target_lights
                data:
                  transition: "{{ transition_time }}"

    default: []
