blueprint:
  name: Motion Time-of-Day Scenes with Override
  description: |
    Schaltet je nach Tageszeit unterschiedliche Szenen per Bewegungsmelder.

    Features:
    - 4 Tageszeit-Szenen (Morgen, Tag, Abend, Nacht) - alle optional
    - Automatischer Szenen-Wechsel bei Tageszeit-Änderung
    - Automatisches Ausschalten wenn neue Tageszeit keine Szene hat
    - Override-Schalter für helle Arbeitsszene mit Auto-Timeout
    - Optionale Helligkeitsprüfung (nur bei Dunkelheit aktivieren)
    - Blocker Entity zum Deaktivieren der Automatik
    - Dim-Warnung vor Ausschalten
    - Device Tracker (nur wenn zuhause)
    - Sanfte Übergänge
  domain: automation
  source_url: https://github.com/hoizi89/ha-blueprints/blob/main/automation/motion_time_of_day_scenes.yaml
  author: hoizi89

  input:
    motion_sensor:
      name: Bewegungsmelder
      description: Binary Sensor für Bewegung
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy

    illuminance_sensor:
      name: Helligkeitssensor (optional)
      description: Wenn gesetzt, wird nur bei Dunkelheit das Licht aktiviert.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    illuminance_threshold:
      name: Helligkeitsschwelle (Lux)
      description: Unter diesem Wert gilt es als dunkel.
      default: 50
      selector:
        number:
          min: 0
          max: 1000
          step: 5
          unit_of_measurement: lx
          mode: slider

    override_switch:
      name: Override-Schalter (Wandschalter / Shelly)
      description: Schalter für die helle Override-Szene.
      selector:
        entity:
          domain:
            - switch
            - input_boolean
            - light

    target_lights:
      name: Lichter/Gruppe zum Ausschalten
      description: Diese Lichter werden bei Bewegungsende ausgeschaltet.
      selector:
        target:
          entity:
            domain: light

    morning_scene:
      name: Morgenszene (optional)
      description: Szene für den Morgen. Wenn leer, wird das Licht ausgeschaltet.
      default: ""
      selector:
        entity:
          domain: scene

    day_scene:
      name: Tagszene (optional)
      description: Szene für den Tag. Wenn leer, wird das Licht ausgeschaltet.
      default: ""
      selector:
        entity:
          domain: scene

    evening_scene:
      name: Abendszene (optional)
      description: Szene für den Abend. Wenn leer, wird das Licht ausgeschaltet.
      default: ""
      selector:
        entity:
          domain: scene

    night_scene:
      name: Nachtszene (optional)
      description: Szene für die Nacht. Wenn leer, wird das Licht ausgeschaltet.
      default: ""
      selector:
        entity:
          domain: scene

    override_scene:
      name: Override-Szene (hell / Arbeitslicht)
      description: Szene wenn Override-Schalter eingeschaltet wird.
      selector:
        entity:
          domain: scene

    off_delay:
      name: Ausschaltverzögerung (Sekunden)
      description: Zeit nach letzter Bewegung bis zum Ausschalten.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          step: 5
          unit_of_measurement: seconds
          mode: slider

    override_timeout:
      name: Override Auto-Aus (Sekunden)
      description: Override-Licht nach dieser Zeit ohne Bewegung automatisch ausschalten. 0 = nie.
      default: 1800
      selector:
        number:
          min: 0
          max: 7200
          step: 60
          unit_of_measurement: seconds
          mode: slider

    transition_time:
      name: Übergangszeit (Sekunden)
      description: Sanfter Übergang beim Schalten.
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: seconds
          mode: slider

    dim_before_off:
      name: Dimmen vor Ausschalten
      description: Licht dimmen als Warnung bevor es ausgeht.
      default: false
      selector:
        boolean: {}

    dim_level:
      name: Dim-Level (%)
      description: Auf diesen Wert dimmen als Warnung.
      default: 20
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"
          mode: slider

    dim_duration:
      name: Dim-Dauer (Sekunden)
      description: Warndauer bevor das Licht ausgeht.
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: seconds
          mode: slider

    morning_start:
      name: Start Morgen
      description: Ab dieser Uhrzeit gilt die Morgenszene.
      default: "06:00:00"
      selector:
        time: {}

    day_start:
      name: Start Tag
      description: Ab dieser Uhrzeit gilt die Tagszene.
      default: "09:00:00"
      selector:
        time: {}

    evening_start:
      name: Start Abend
      description: Ab dieser Uhrzeit gilt die Abendszene.
      default: "17:00:00"
      selector:
        time: {}

    night_start:
      name: Start Nacht
      description: Ab dieser Uhrzeit gilt die Nachtszene (bis Morgen).
      default: "22:00:00"
      selector:
        time: {}

    blocker_entity:
      name: Blocker Entity (optional)
      description: Wenn ON, wird die Automatik deaktiviert (z.B. Filmabend).
      default: ""
      selector:
        entity:
          domain:
            - input_boolean
            - switch
            - binary_sensor

    person_home:
      name: Device Tracker / Person (optional)
      description: Nur aktivieren wenn zuhause.
      default: ""
      selector:
        entity:
          domain:
            - person
            - device_tracker

mode: restart
max_exceeded: silent

variables:
  illuminance_sensor: !input illuminance_sensor
  illuminance_threshold: !input illuminance_threshold
  blocker_entity: !input blocker_entity
  person_home: !input person_home
  morning_scene: !input morning_scene
  day_scene: !input day_scene
  evening_scene: !input evening_scene
  night_scene: !input night_scene
  override_scene: !input override_scene
  transition_time: !input transition_time
  dim_before_off: !input dim_before_off
  dim_level: !input dim_level
  dim_duration: !input dim_duration
  override_timeout: !input override_timeout
  morning_start: !input morning_start
  day_start: !input day_start
  evening_start: !input evening_start
  night_start: !input night_start

  now_minutes: "{{ now().hour * 60 + now().minute }}"
  morning_minutes: "{{ (morning_start.split(':')[0] | int) * 60 + (morning_start.split(':')[1] | int) }}"
  day_minutes: "{{ (day_start.split(':')[0] | int) * 60 + (day_start.split(':')[1] | int) }}"
  evening_minutes: "{{ (evening_start.split(':')[0] | int) * 60 + (evening_start.split(':')[1] | int) }}"
  night_minutes: "{{ (night_start.split(':')[0] | int) * 60 + (night_start.split(':')[1] | int) }}"

  is_morning: "{{ morning_minutes <= now_minutes < day_minutes }}"
  is_day: "{{ day_minutes <= now_minutes < evening_minutes }}"
  is_evening: "{{ evening_minutes <= now_minutes < night_minutes }}"
  is_night: "{{ now_minutes >= night_minutes or now_minutes < morning_minutes }}"

  has_blocker: "{{ blocker_entity | length > 0 }}"
  is_blocked: "{{ has_blocker and states(blocker_entity) == 'on' }}"

  has_person_check: "{{ person_home | length > 0 }}"
  is_person_home: "{{ not has_person_check or states(person_home) == 'home' }}"

  has_illuminance: "{{ illuminance_sensor | length > 0 }}"
  is_dark: "{{ not has_illuminance or (states(illuminance_sensor) | float(0)) < illuminance_threshold }}"

  has_morning_scene: "{{ morning_scene | length > 0 }}"
  has_day_scene: "{{ day_scene | length > 0 }}"
  has_evening_scene: "{{ evening_scene | length > 0 }}"
  has_night_scene: "{{ night_scene | length > 0 }}"

  current_scene: >
    {% if is_morning and has_morning_scene %}
      {{ morning_scene }}
    {% elif is_day and has_day_scene %}
      {{ day_scene }}
    {% elif is_evening and has_evening_scene %}
      {{ evening_scene }}
    {% elif is_night and has_night_scene %}
      {{ night_scene }}
    {% else %}
      none
    {% endif %}

  has_current_scene: "{{ current_scene != 'none' }}"
  can_activate: "{{ not is_blocked and is_person_home and is_dark }}"

triggers:
  - id: motion_on
    trigger: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

  - id: motion_off
    trigger: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"

  - id: override_on
    trigger: state
    entity_id: !input override_switch
    to: "on"

  - id: override_off
    trigger: state
    entity_id: !input override_switch
    to: "off"

  - id: time_morning
    trigger: time
    at: !input morning_start

  - id: time_day
    trigger: time
    at: !input day_start

  - id: time_evening
    trigger: time
    at: !input evening_start

  - id: time_night
    trigger: time
    at: !input night_start

conditions: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: override_on
        sequence:
          - action: scene.turn_on
            target:
              entity_id: "{{ override_scene }}"
            data:
              transition: "{{ transition_time }}"

      - conditions:
          - condition: trigger
            id: override_off
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input motion_sensor
                    state: "on"
                  - condition: template
                    value_template: "{{ can_activate and has_current_scene }}"
                sequence:
                  - action: scene.turn_on
                    target:
                      entity_id: "{{ current_scene }}"
                    data:
                      transition: "{{ transition_time }}"
            default:
              - action: light.turn_off
                target: !input target_lights
                data:
                  transition: "{{ transition_time }}"

      - conditions:
          - condition: trigger
            id: motion_on
          - condition: state
            entity_id: !input override_switch
            state: "off"
          - condition: template
            value_template: "{{ can_activate and has_current_scene }}"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: "{{ current_scene }}"
            data:
              transition: "{{ transition_time }}"

      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input override_switch
            state: "off"
        sequence:
          - delay:
              seconds: !input off_delay
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
          - condition: state
            entity_id: !input override_switch
            state: "off"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ dim_before_off }}"
                sequence:
                  - action: light.turn_on
                    target: !input target_lights
                    data:
                      brightness_pct: "{{ dim_level }}"
                      transition: "{{ transition_time }}"
                  - delay:
                      seconds: "{{ dim_duration }}"
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input motion_sensor
                            state: "on"
                          - condition: template
                            value_template: "{{ has_current_scene }}"
                        sequence:
                          - action: scene.turn_on
                            target:
                              entity_id: "{{ current_scene }}"
                            data:
                              transition: "{{ transition_time }}"
                    default:
                      - action: light.turn_off
                        target: !input target_lights
                        data:
                          transition: "{{ transition_time }}"
            default:
              - action: light.turn_off
                target: !input target_lights
                data:
                  transition: "{{ transition_time }}"

      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input override_switch
            state: "on"
          - condition: template
            value_template: "{{ override_timeout > 0 }}"
        sequence:
          - delay:
              seconds: "{{ override_timeout }}"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
          - condition: state
            entity_id: !input override_switch
            state: "on"
          - action: homeassistant.turn_off
            target:
              entity_id: !input override_switch

      - conditions:
          - condition: trigger
            id:
              - time_morning
              - time_day
              - time_evening
              - time_night
          - condition: state
            entity_id: !input override_switch
            state: "off"
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
          - condition: template
            value_template: "{{ can_activate }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ has_current_scene }}"
                sequence:
                  - action: scene.turn_on
                    target:
                      entity_id: "{{ current_scene }}"
                    data:
                      transition: "{{ transition_time }}"
            default:
              - action: light.turn_off
                target: !input target_lights
                data:
                  transition: "{{ transition_time }}"

    default: []
